services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge